### ISSUE TITLE
CTR-01, REL-02 domain types, no access to 0-10v

### ISSUE THREAD

**Issue by bipbopbap** [thomasloven/hass_plejd#12]
My CTR-01 that is configured as relay other (not relay light) turns up as a switch in ha.
The switch domain does not give access to the 0-10v output of the CTR-01.
I currently use the output to control a fan.
I understand that I could wrap the switch in fan entity using template, but that would not give me access to 0-10v output.
I could change the type in plejd configuration to relay light, but that would disable the timer feature of plejd....
Maybe it would be prefered to always use the light domain in ha?

The REL-02 configured as relay light gives you access to brightness which does not exist on the REL-02 since it does not have a 0-10v output.
This can possibly be wrapped in a switch using template to hide the brightness

**Comment by thomasloven** [comment]
Is this still an issue?

**Comment by Kiachma** [comment]
Hi,
I'm still experiencing the same behavior. My ctr-01 is connected to a fan and im able to control the voltage via the plejd app. It, however shows up as a plain light without the ability to dim in HA. Is it something that i have to configure or should it work out of the box? 

![Image](https://github.com/user-attachments/assets/49ede62a-bc29-4518-9f1e-88d16dc572aa)

**Comment by thomasloven** [comment]
Thanks for searching first!
But please open a new issue
