### ISSUE TITLE
Entity names are too long

### ISSUE THREAD

**Issue by bnordli** [thomasloven/hass_plejd#16]
Entity names are now similar to "Plejd REL-02 {plejdName}" where {plejdName} is the name given in the Plejd app.

I think the default entity name should just be the same as in the Plejd app (like I think it was before).

**Comment by astrandb** [comment]
I agree that the entity names are too long. The model is clearly visible in the device views and has limited value in daily use.
The Shelly integration describe their algorithm for default entity names in detail [in HA docs](https://www.home-assistant.io/integrations/shelly/#entity-naming-generation-1.) Perhaps something to take inspiration from.

**Comment by Davst** [comment]
I agree. currently the device name isn't really interesting for the end user. the controls are what amounts to a light.

**Comment by SM6WGG** [comment]
Changing def device_info(self): "name": to be self.device.name and remove the def name(self): property in switch.py and light.py worked like a charm for me. Now devices are using the Plejd names insted of brandname followed by device model and entity id's are the same. 
 
Love the intergration so far! Lightning fast and easy to use/install. and seem to work flawelessly toghether with other bluetooth devices on the same adapter!
