### ISSUE TITLE
"Software caused connection abort"

### ISSUE THREAD

**Issue by Gahrlaag** [thomasloven/hass_plejd#17]
I get the following error when trying to setup plejd.
Logger: custom_components.plejd.pyplejd.mesh
Source: custom_components/plejd/pyplejd/mesh.py:86
Integration: Plejd
First occurred: 21:19:46 (1 occurrences)
Last logged: 21:19:46

Error connecting to Plejd device: plejd - E3:FA:36:97:C3:BC: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort

Also, I always end up getting two integrations

**Comment by thomasloven** [comment]
This has been open for way too long with no action from my side.
I'll assume this is fixed by updating Home Assistant, any esphome BT proxies and hass_plejd.

If not, please open a new issue.
