### ISSUE TITLE
Device CTR-01 

### ISSUE THREAD

**Issue by mudape** [thomasloven/hass_plejd#2]
Hi,
First, thanks for making this. 
I just switch from hassio-plejd on RPi4 (HASSOS) to this on docker using ESP32. Very happy :)

Noticed that Plejd [CTR-01](https://www.plejd.com/sv-se/produkter/CTR-01) is set to non-dimmable.
The device can act as relay but also dim depending on its config.

I changed dimmable to True, works great https://github.com/thomasloven/hass_plejd/blob/49e97e0a72cd65a026ee8919d6b14dc04906fded/custom_components/plejd/pyplejd/plejd_device.py#L19 

If acting as a relay Plejd hopefully tells (?)
https://github.com/thomasloven/hass_plejd/blob/49e97e0a72cd65a026ee8919d6b14dc04906fded/custom_components/plejd/pyplejd/api.py#L86-L87

**Comment by thomasloven** [comment]
Fixed
