### ISSUE TITLE
Some performance and integration issues

### ISSUE THREAD

**Issue by alekslyse** [thomasloven/hass_plejd#20]
I tried to get this working with some Plejd dimmers, but cant really get it working. In the start I tried with the gateway, then removed the gateway. HA finds the dimmers, they include, but HA cant connect to the mesh. When I used the gateway it managed to connect to the mesh, but the response was so delayed. Is it supposed to be direct response as I wanted to control the hue lights with the dimmers in realtime, but this one for me is 2-10 seconds delayed. Also after the dimmer is located in HA, and added the entity is grayed out, and never goes online

**Comment by thomasloven** [comment]
This is not supposed to work with the plejd gateway at all. It's supposed to work with a direct bluetooth connection.

**Comment by alekslyse** [comment]
> This is not supposed to work with the plejd gateway at all. It's supposed to work with a direct bluetooth connection.

Yes, I tried to install without the gateway too, but the response is several seconds. It might be because I only have physical dimmers, no “pucks”? Even if the integration find the dimmers they are greyed out in HA and the way I see the response is in debug

**Comment by oyvindwe** [comment]
As I understand it, the dimmers (VRI-02) are just pucks with the RTR-01 adapter attached.

@alekslyse What kind of bluetooth device are you using? Any log files you can share?

**Comment by alekslyse** [comment]
I have the WRT-01-EW. I just set everything up again to test. The response after I click a button is about 10-15 seconds. The turning of the dimmer wheel is not working at all.

I just added 4 dimmers to the setup, and nothing else (I just have dimmers)

Attached is the debug log from HA
[2023-02-12 17:16:23.log](https://github.com/thomasloven/hass_plejd/files/10716553/2023-02-12.17.16.23.log)

**Comment by oyvindwe** [comment]
I'm not sure I understand your setup. If you have WRT, it must be paired with a puck. You set this up in the Plejd app.

I'm also a bit puzzled by `Authentication failed` towards one address. Have you configured this as separate mesh networks?

**Comment by alekslyse** [comment]
> I'm not sure I understand your setup. If you have WRT, it must be paired with a puck. You set this up in the Plejd app.
> 
> I'm also a bit puzzled by `Authentication failed` towards one address. Have you configured this as separate mesh networks?

My goal was to use the dimmer only, then respond to it with an automation on non plejd things. Seem like this is not possible

**Comment by oyvindwe** [comment]
> My goal was to use the dimmer only, then respond to it with an automation on non plejd things. Seem like this is not possible

I see. No, as I understand it, turning the wheel on WRT only sends direct messages to the DIM unit it is paired with. I believe you can capture double clicks (scene triggers) in realtime, but the scene has to actually do something with a Plejd puck.

**Comment by alekslyse** [comment]
> > My goal was to use the dimmer only, then respond to it with an automation on non plejd things. Seem like this is not possible
> 
> I see. No, as I understand it, turning the wheel on WRT only sends direct messages to the DIM unit it is paired with. I believe you can capture double clicks (scene triggers) in realtime, but the scene has to actually do something with a Plejd puck.

Alright. I just got it suggested on a facebook group. Then its not possible, and I will just return the dimmers :)

**Comment by thomasloven** [comment]
Yes, this seems to be true unfortunately. The plejd rotational dimmers can not be used with anything but plejd devices except possibly for toggling on/off.
