### ISSUE TITLE
A quick update

### ISSUE THREAD

**Issue by thomasloven** [thomasloven/hass_plejd#21]
Hi!

You may have noticed I have not put much work into this during the last couple of months.
The reason for this is twofold.
First, there's been a huge influx of stuff to do at work.

Second, and more importantly, my daughters wanted their own room, so I had to move out of my home office, and since packing that up I haven't been able to find all the hardware I was using for testing this stuff again...
I'm sure it's somewhere, and whenever I can locate it again I will pick this back up.

/ Thomas

**Comment by magicus** [comment]
You seemed to have picked up speed again the last few months? Maybe this note is past its useful date...
