### ISSUE TITLE
Suppport for two different mesh?

### ISSUE THREAD

**Issue by NachoMas** [thomasloven/hass_plejd#22]
Hi! I have a special situation with two different mesh, one in the house and one on the garage because of physical distance. The house one is using the integration flawlessly and all plejd pucks are autodiscovered and work. Now, I'm trying to use the Theengsgateway (BT to MQTT) to discover as well the plejd mesh in the garage and I can see that the BT gw does see the Plejd puck even if it does not add it as lights in the autodiscovery topic (I've asked about that in another thread). Will the integration be able to discover the second mesh and add it if home assistant adds the single Plejd puck in the garage mesh as a light in the autodiscovery topic? Will it then start a second integration instance or arr the second mesh to the same instance? Thanks!

**Comment by thomasloven** [comment]
This should work now.
The first mesh will be auto discovered. Then you can add more manually.
