### ISSUE TITLE
101% brightness reported

### ISSUE THREAD

**Issue by FreshJonte** [thomasloven/hass_plejd#23]
Hello, I have this small issue where brightness is reported as 101% when at full brightness. Plejd device is DIM-01. Anyone have a solution for this? Thanks!
![2023-02-15 19_54_24-Dashboard – Home Assistant](https://user-images.githubusercontent.com/65363113/219125556-6ccde15f-9ac3-46e4-a8d2-1fb1bf4b84a6.png)
![2023-02-15 19_54_57-Developer Tools – Home Assistant](https://user-images.githubusercontent.com/65363113/219125559-5b4463f9-ceb6-4430-8991-0c265dbe9311.png)

**Comment by pissten** [comment]
Same for me
