### ISSUE TITLE
Feature request: Events

### ISSUE THREAD

**Issue by ricmik** [thomasloven/hass_plejd#24]
Thanks for creating this awesome project!

Would it be possible to send events to the event bus or similar to be able to automate on specific events on the Plejd mesh?

It would be really useful to create automations on events like this one:
[custom_components.plejd.pyplejd.mesh] Scene triggered: {'scene': 9}

This event could trigger an automation to do additional scene activations or disabling/enabling other automations in Home Assistant.

**Comment by thomasloven** [comment]
That's a work in progress. See #7
