### ISSUE TITLE
Plejd buttons (WPH-01) are unavailable

### ISSUE THREAD

**Issue by kristofferR** [thomasloven/hass_plejd#31]
I've installed this, and it mostly works fine, but my two WPH-01 (Firmware: 0.4.0) switches are unavailable. 

I've enabled debug logging, but I still don't see anything in the log.

**Comment by thomasloven** [comment]
Do they become available if you press on them?
If not, do they become available if you press the same button twice?
It's a bit hard to know whith those, since they send different events (or none at all) depending on how they are configured...

**Comment by kristofferR** [comment]
Nope, I've pressed the buttons a bunch, and they haven't ever been available since installing hass_plejd.

**Comment by thomasloven** [comment]
What are their functions set to in the plejd app?

**Comment by kristofferR** [comment]
They're set to a scenario now, but it doesn't seem to matter, it didn't work even when not set to anything.

**Comment by kristofferR** [comment]
I deleted one of the WPH-01 in the Plejd app and readded it, now it worked. Seems like that solved it 🙂

How do I use the four inputs of the switch in an automation though?

**Comment by thomasloven** [comment]
WPH-01 should now (as of two minutes) register as two to four event entities instead of as a switch.

**Comment by kristofferR** [comment]
Awesome, works great, thanks!
