### ISSUE TITLE
Add events for RTR-01 (and other rotating dimmers)

### ISSUE THREAD

**Issue by kristofferR** [thomasloven/hass_plejd#32]
Thanks for adding events to WPH-01! I've now been able implenent toggle on/off functionality for those switches, which makes way more sense IMO than having to press the right part of the switches to turn them on/off.

I have a bunch of RTR-01 that also would be helpful to add events to. 

If the rotating motion could be made into events that would be ideal, as I could use that to control the brightness of Hue lights, but I'd also be happy with just the button press being an event.

**Comment by thomasloven** [comment]
RTR-01 is not a separate device, but instead acts similar to a switch connected to the puck. Therefore it doesn't publish any events to the bluetooth mesh other than what you can get from the connected puck itself.

It also seems that the wireless dimmer WRT-01 does not publish rotational events to the mesh, but instead communicates directly with whatever device it has been paired to - meaning they can't be overheard by hass.

**Comment by kristofferR** [comment]
Ah, that's a shame. Thanks for your help!
