### ISSUE TITLE
Got Time Data Warning in the log

### ISSUE THREAD

**Issue by johanschelin** [thomasloven/hass_plejd#33]
After updating to the 47dd23a version, i get this error continously in the log. At the same day, I have added an extender EXT-01 which also could potentially be the cause of the issue.

Started debug logging and attaches the log from times when it happens.
[home-assistant_plejd_2023-08-21T20-39-24.953Z.log](https://github.com/thomasloven/hass_plejd/files/12402362/home-assistant_plejd_2023-08-21T20-39-24.953Z.log)

**Comment by thomasloven** [comment]
Ah. I accidentally left that one in there from debugging.
It's not an actual problem. You can ignore the warning until I can remove it.

**Comment by johanschelin** [comment]
Ok!

Med vänlig hälsning,
Johan Schelin
________________________________
Från: Thomas Lovén ***@***.***>
Skickat: Tuesday, August 22, 2023 7:11:33 AM
Till: thomasloven/hass_plejd ***@***.***>
Kopia: Johan Schelin ***@***.***>; Author ***@***.***>
Ämne: Re: [thomasloven/hass_plejd] Got Time Data Warning in the log (Issue #33)


Ah. I accidentally left that one in there from debugging.
It's not an actual problem. You can ignore the warning until I can remove it.
