### ISSUE TITLE
Issue with naming of the "parent device"

### ISSUE THREAD

**Issue by ricmik** [thomasloven/hass_plejd#36]
There is a logical issue with naming of the parent device when the device has two outputs in different rooms.
I have a Plejd DIM-02 with outputs in two different rooms on two different floors. This creates some issues in the naming of the device in the Plejd integration and the configured area in Home Assistant integration.

If I try to change the area in Home Assistant of one of the outputs (lights), the parent device also changes area, thus changing the area for both outputs of the device in the operation.

In the example below I have a DIM-02 that originally was named "Taklampe Soverom" by the Plejd integration with one output enabled initially, - also called "Taklampe Soverom". I then configured output 2 as a dummy output as a workaround do scene events in Home Asisstant without actually making changes on the lights in the house. Suddenly the parent device is called "Dummy" with the outputs (lights) "Taklampe Soverom" and "Dummy". If I change the area of the "Dummy"-light to another room, the parent device also changes area".

<img width="800" alt="bilde" src="https://github.com/thomasloven/hass_plejd/assets/6681390/153f1e23-d558-43eb-9510-429a7073c030">

<img width="300" alt="bilde" src="https://github.com/thomasloven/hass_plejd/assets/6681390/09b3fad2-3857-4ce2-aed0-58e773750ed6">

<img width="300" alt="bilde" src="https://github.com/thomasloven/hass_plejd/assets/6681390/7110d331-cc88-43d1-ac58-15e643024c74">

**Comment by thomasloven** [comment]
I've tried to explain this to the Home Assistant core team, but "one device is one device".
I'll bring this post up to try to convince them otherwise.

In the mean time, you can select for each entity to not use the device area:
<img width="295" alt="image" src="https://github.com/thomasloven/hass_plejd/assets/1299821/d8efc6a1-8c96-4610-ad0b-58b6a1c75db8">

**Comment by ricmik** [comment]
Yeah, I can see the concept of "one device is one device" since it actually is just one device with two outputs 😄 
Changing the entity area might help, I'll see if that'll do it.

Anyway, I'm not sure how the device could have been named in order to better reflect the actual device. But right now it's a bit confusing. I see in the Plejd app that the device from my example is "Type: DIM-02", "Name: Soverommet, Dummy" maybe it would help using this name when naming the device in Home Assistant (if that name is available on the Plejd mesh)

**Comment by thomasloven** [comment]
I noticed Plejd name the devices from the two outputs.
The problem with using that device name is that would mean your entities get named "Soverommet, Dummy Soverommet" and "Soverommet, Dummy Dummy", which is less than ideal...

**Comment by ricmik** [comment]
I must say that I prefer the previous naming since the devices are handled the way they are.

light.{device_type}_{output_name}

Example:
light.plejd_dim_01_2p_soverommet is better than light.soverommet_soverommet (which also gives the display name Dummy Taklampe Soverommet in my case, making a discrepancy between the display name and device name).

**Comment by thomasloven** [comment]
The naming scheme has been updated.
