### ISSUE TITLE
Adding DWN-02

### ISSUE THREAD

**Issue by Kimrobin98** [thomasloven/hass_plejd#39]
Hi, i curently have 18 plejd downlight in different rooms, previously these showed up as dimmers but they have now turned in to swiches. That means im unable to dim the ligts at the moment. I get that the DWN-02 might not be supported yet, but i would atleast like to get the dimming backup, and if possible the color temprature control would be an awsome addition.

**Comment by thomasloven** [comment]
Could you go into the Integration settings, download the Diagnostic data and send that to me?

Depending on your setup that data may contain your address and/or map coordinates, so feel free to send it by email.

![bild](https://github.com/thomasloven/hass_plejd/assets/1299821/5870f49f-5158-4382-a6c1-cf95f31a96b1)

**Comment by Kimrobin98** [comment]
You should have the diagnostics in your mailbox now, im realy amazed by the fast replay. Thanks againg! :)

**Comment by Kimrobin98** [comment]
any updates?

**Comment by thomasloven** [comment]
I hope DNW-01 and DWN-02 should work now.
They seem to report as non-dimmable from the cloud API data, though, which is odd.

Could you perhaps help with collecting some data for the color temperature?

By adding the following to your `configuration.yaml` file and restarting hass:
```yaml
logger:
  default: warn
  logs:
    custom_components.plejd: debug
    pyplejd: debug
```
This should give a lot of output to the file `home-assistant.log`
There, the interesting parts would be lines starting with:
`2023-10-11 20:57:56.230 DEBUG (MainThread) [pyplejd.ble] DIM Message: b'...`
or
`2023-10-11 20:58:23.029 DEBUG (MainThread) [pyplejd.ble] Unknown cmd (b'...`

If you could capture a few lines like that which appear when you change the color temperature, there might be some interesting information in them. Obviously knowing roughly which line relates to what action would be absolutely fantastic, but I realize it can be a lot of data and really hard to know what you catch.
