### ISSUE TITLE
Integration stopped working after upgrade

### ISSUE THREAD

**Issue by johanschelin** [thomasloven/hass_plejd#43]
After upgrade to 3.0.3 the integration wont start. Even downgrading via HACS to 3.0.1. or 3.0.0 fails with same error.

Below from HA log, and also attaching a debug log. Is it something in my end, or did something break in the update?

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 00:00:21 (4 occurrences)
Last logged: 00:24:26

Error setting up entry Karpvägen 26 (19 devices) for plejd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plejd/__init__.py", line 29, in async_setup_entry
    await plejdManager.init()
  File "/usr/local/lib/python3.11/site-packages/pyplejd/__init__.py", line 48, in init
    self.devices = self.cloud.devices
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplejd/cloud/__init__.py", line 159, in devices
    outputType = const.DEVICES.HARDWARE_TYPE[hardware]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '-unknown- (19)'


[home-assistant_plejd_2023-10-03T22-24-29.186Z.log](https://github.com/thomasloven/hass_plejd/files/12797370/home-assistant_plejd_2023-10-03T22-24-29.186Z.log)

**Comment by johanschelin** [comment]
Partial restore of the HA Core got it up and running again - going back to 3.0.1 together with the rest of the Core.

**Comment by thomasloven** [comment]
This should be fixed now.

**Comment by thomasloven** [comment]
Actually, it probably isn't fixed at all... I'll make a new release momentarily

**Comment by johanschelin** [comment]
Many thanks Thomas, can confirm that my issue is solved! Great work

**Comment by thomasloven** [comment]
You may or may not have a new device of model `-unknown- (19)`. It could be interesting for the future to know if you happen to know what that is?

**Comment by thomasloven** [comment]
Thanks!
I deleted your comment since the debugging data contains your address.

**Comment by johanschelin** [comment]
Ouch, should have read more carefully. Thanks for deletion!
