### ISSUE TITLE
Missing double click buttons from WPH-01

### ISSUE THREAD

**Issue by oleost** [thomasloven/hass_plejd#50]
The WPH-01 buttons have double click function to enable more functionality from them.

Is there a way to listen to these buttons expect creating a scene and then listening for that scene?

![image](https://github.com/thomasloven/hass_plejd/assets/5670710/217fe078-ba1f-4241-9a79-d480bdb07eb7)

**Comment by thomasloven** [comment]
The double click functionality can *only* be used to trigger scenarios, and can only be set up from the plejd app.
