### ISSUE TITLE
Integration not loading with 2024.1.0b2

### ISSUE THREAD

**Issue by johanschelin** [thomasloven/hass_plejd#51]
Testing the latest beta makes Plejd integration not load at all - probably this error is all you need?

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 15:53:59 (21 occurrences)
Last logged: 15:53:59

Error occurred loading flow for integration plejd: No module named 'home_assistant_bluetooth.models'

**Comment by thomasloven** [comment]
Thanks. I noticed that one and will release a fix in a few hours.

**Comment by johanschelin** [comment]
Many thanks! I can test and verify once it is released.

**Comment by thomasloven** [comment]
0.6.0 has been released and should fix this.
