### ISSUE TITLE
Support of Devices DAL-01 & REL-02

### ISSUE THREAD

**Issue by L1ttl3b4k3r** [thomasloven/hass_plejd#52]
I own several Plejd units i.e. DAL-01 and REL-02 and wondering how I could contribute to the further development.

**Comment by thomasloven** [comment]
Hi. Thanks for reaching out!

With a bit of luck, version 0.7.0 should be able to pick up your DAL-01 and REL-02 devices in *some* way and list them as devices under the Plejd integration.
With even more luck, they may even give you lights and switches as expected - though I expect DAL-01 in particular to be... weird...
Anyway; when you open them up, you'll likely find a number in parantheses near the top left, in the Device Info box.
I need that number.
![image](https://github.com/thomasloven/hass_plejd/assets/1299821/8562ddf8-1165-4d0c-acc2-c44920f1f707)


The file you get when clicking "Download Diagnostics" would also be appreciated.
It should be cleaned of any sensitive data, but make sure to scroll through it anyway.

**Comment by L1ttl3b4k3r** [comment]
Hi Thomas,

please find the device info as followed:
REL-02: "REL-02 by Plejd"
DIM-01: "DIM-01-LC by Plejd"
DAL-01: "-unknown- (12) by Plejd"

I'm presently struggling with obtaining the diagnostics file, an empty page opened while clicking the download button.
Any advice in this regard is appreciated, neverteless I try to figure out the reason.

**Comment by L1ttl3b4k3r** [comment]
Beside light.dali01 itself, no further entities were created.
Nevertheless the light card allows also to set the brightness 
![grafik](https://github.com/thomasloven/hass_plejd/assets/65508342/fcaa7af4-b57c-4424-8653-605a6c01a539)
and light color 
![grafik](https://github.com/thomasloven/hass_plejd/assets/65508342/d578f3e2-201c-42b8-8997-0ada949550df)

I own only a single DALI bus light for trial purpose. I assume, all bus connected lights could be controlled.

**Comment by thomasloven** [comment]
DAL-01 is added to version 0.8.0.
Thanks for your input!
