### ISSUE TITLE
Only HA or app connects - not both at the same time.

### ISSUE THREAD

**Issue by astrandb** [thomasloven/hass_plejd#6]
Thank you for your efforts with this integration. It looks very promising.
However I have found  a problem. 
My setup is:
- HA with a ESPHome bt-proxy (no Bluetooth in the HA server)
- One DIM-01
- No Plejd gateway
I can control the dimmer as expected from the app only if I disconnect the bt-proxy and vice versa. When the bt-proxy is connected the IOS app does not connect via bluetooth. When the App is connected to the dimmer, HA/bt-proxy does not connect.

**Comment by thomasloven** [comment]
That's a known limitation of the plejd system.
You can only connect one controller per device in the mesh at a time.
