### ISSUE TITLE
Multiple copies of integrations shown upon bluetooth discovery

### ISSUE THREAD

**Issue by bnordli** [thomasloven/hass_plejd#8]
This happened when I wanted to start from a clean slate by deleting the integration and setting it up again.

![image](https://user-images.githubusercontent.com/5574761/198123581-fc973a3b-16c4-4b1d-8ae0-ce9adaa2be24.png)

HA is probably listing one copy of the integration per device/puck which offers the Plejd service, but since it is a mesh, it doesn't make sense to list more than one.

(This list is still present after configuring, but goes away after a restart.)

**Comment by thomasloven** [comment]
Yeah... there's currently no way to prevent this, unfortunately.

**Comment by bnordli** [comment]
I see. I imagine there are several bluetooth mesh integrations out there. How do they solve it? If the haven't, wouldn't it be useful to add (and implement) a `mesh` boolean to the `bluetooth` part of `manifest.json` to tell HA only to list one copy?

**Comment by thomasloven** [comment]
Bluetooth discovery is fairly new, so I don't think it's become a problem yet. But it definitely will be, so I will make sure it's looked into.

**Comment by oyvindwe** [comment]
Maybe it's better to remove bluetooth discovery and only support user driven setup?

Most likely the user just installed the component using HACS, so clicking an extra button and search for "Plejd" to setup  the integration isn't a major UX setback.

**Comment by thomasloven** [comment]
I got some help from the Hass core team with this one. It should only show one discovery notification now.
